# Generated by Django 4.2 on 2023-04-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default="", max_length=30)),
                ("price", models.DecimalField(decimal_places=1, max_digits=20)),
            ],
        ),
    ]
